"""fixed the database

Revision ID: 22fa2d1605e0
Revises: cdb6e983a874
Create Date: 2024-02-28 03:05:59.694501

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22fa2d1605e0"
down_revision: Union[str, None] = "cdb6e983a874"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classrroms")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classrroms",
        sa.Column("name", sa.VARCHAR(length=60), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(length=60), autoincrement=False, nullable=True),
        sa.Column("id", sa.VARCHAR(length=60), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="classrroms_pkey"),
    )
    # ### end Alembic commands ###
