"""fixed error in the database

Revision ID: 61c96f5f13dd
Revises: 22fa2d1605e0
Create Date: 2024-02-28 03:39:42.775671

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61c96f5f13dd"
down_revision: Union[str, None] = "22fa2d1605e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assignments", sa.Column("class_room_id", sa.String(length=60), nullable=False))
    op.add_column("assignments", sa.Column("user_id", sa.String(length=60), nullable=False))
    op.create_foreign_key(None, "assignments", "class_rooms", ["class_room_id"], ["id"])
    op.create_foreign_key(None, "assignments", "users", ["user_id"], ["id"])
    op.drop_column("assignments", "classroom_id")
    op.create_foreign_key(None, "class_rooms", "users", ["user_id"], ["id"])
    op.add_column("resources", sa.Column("class_room_id", sa.String(length=60), nullable=False))
    op.create_foreign_key(None, "resources", "class_rooms", ["class_room_id"], ["id"])
    op.create_foreign_key(None, "resources", "users", ["user_id"], ["id"])
    op.drop_column("resources", "class_id")
    op.add_column("submitted_assignments", sa.Column("assignment_id", sa.String(length=60), nullable=False))
    op.alter_column(
        "submitted_assignments",
        "resource_link",
        existing_type=sa.VARCHAR(length=60),
        type_=sa.String(length=250),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "submitted_assignments", "assignments", ["assignment_id"], ["id"])
    op.create_foreign_key(None, "submitted_assignments", "users", ["user_id"], ["id"])
    op.drop_column("submitted_assignments", "classroom_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submitted_assignments", sa.Column("classroom_id", sa.VARCHAR(length=60), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "submitted_assignments", type_="foreignkey")
    op.drop_constraint(None, "submitted_assignments", type_="foreignkey")
    op.alter_column(
        "submitted_assignments",
        "resource_link",
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=60),
        existing_nullable=True,
    )
    op.drop_column("submitted_assignments", "assignment_id")
    op.add_column("resources", sa.Column("class_id", sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_constraint(None, "resources", type_="foreignkey")
    op.drop_constraint(None, "resources", type_="foreignkey")
    op.drop_column("resources", "class_room_id")
    op.drop_constraint(None, "class_rooms", type_="foreignkey")
    op.add_column("assignments", sa.Column("classroom_id", sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_constraint(None, "assignments", type_="foreignkey")
    op.drop_constraint(None, "assignments", type_="foreignkey")
    op.drop_column("assignments", "user_id")
    op.drop_column("assignments", "class_room_id")
    # ### end Alembic commands ###
